/* Main.c file generated by New Project wizard
 *
 * Created:   Wed Nov 20 2019
 * Processor: MSP430G2553
 * Compiler:  CodeComposer for MSP430
 */

#include <msp430.h>
#define delay_ms(x)		__delay_cycles((long) x* 1000)
#define delay_us(x)		__delay_cycles((long) x)

void main()
 { 
   // Write your code here
    P1DIR |= 0b11100000;
     P2DIR |= 0b11111111;
    //P1OUT |=  BIT6 + BIT5 + BIT7;  
    
    P1REN |= (BIT0|BIT1|BIT2|BIT3);
        P1OUT |= (BIT0|BIT1|BIT2|BIT3);
        P1IES &= ~(BIT0|BIT1|BIT2|BIT3);
        P1IE |= (BIT0|BIT1|BIT2|BIT3);
        P1IFG &= ~(BIT0|BIT1|BIT2|BIT3);
    
    _enable_interrupt();
    
    
   while (1){
      P1OUT ^= BIT5;
      delay_ms(50);	
      P1OUT ^= BIT5;
      P1OUT ^= BIT6;
      delay_ms(50);	
      P1OUT ^= BIT6;
      P1OUT ^= BIT7;
      delay_ms(50);
      P1OUT ^= BIT7;
      }
      ;
 }
#pragma vector = PORT1_VECTOR
__interrupt void Port1_isr(void){
	if(P1IFG & BIT1){
	   if(P1OUT & BIT5){
	      P2OUT ^= BIT0;
	      }
	   else if(P1OUT & BIT6){
	      P2OUT ^= BIT1;
	      }
	   else if(P1OUT & BIT7){
	      P2OUT ^= BIT2;
	      }
	}
	if(P1IFG & BIT0){
	 if(P1OUT & BIT5){
	    P2OUT ^= BIT3;
	    }
	     else if(P1OUT & BIT6){
	      P2OUT ^= BIT4;
	      }
	      else if(P1OUT & BIT7){
	      P2OUT ^= BIT5;
	      }
	    
	   }
	   if(P1IFG & BIT2){
	      if(P1OUT & BIT5){
		 P2OUT ^= BIT0;
		 }
	      else if(P1OUT & BIT6){
		 P2OUT ^= BIT4;
		 }
	      else if(P1OUT & BIT7){
		 P2OUT ^= BIT5;
		 }
	}
	 if(P1IFG & BIT3){
	      if(P1OUT & BIT5){
		 P2OUT ^= BIT0;
		 }
	      else if(P1OUT & BIT6){
		 P2OUT ^= BIT4;
		 }
	      else if(P1OUT & BIT7){
		 P2OUT ^= BIT5;
		 }
	}
	P1IFG &= ~(BIT0|BIT1|BIT2|BIT3);

}